version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "quarkus-http"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-195tbnm7awdvq"
s3_prefix = "quarkus-http"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
