name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@v2.0.1

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Setup AWS SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Deploy using AWS SAM CLI
      run: sam deploy -t target/sam.jvm.yaml --config-file ../samconfig.toml
